name = "nautica"
main = "_worker.js"
type = "javascript"
compatibility_date = "2024-09-23 "
compatibility_flags = ["nodejs_compat_v2"]

[build]
upload.format = "modules"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true